### ISSUE TITLE
Text alignment in footer

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/ideas-productivity.github.io#11]
Text in the main portion of the footer is left-justified against the centerline of the footer (=page).  It looks odd.  Especially for longer text, like the call for subscription.

![Capture](https://user-images.githubusercontent.com/426409/236262304-2db0c419-394d-40fb-bb59-bc2f08e812f1.PNG)

**Comment by sbxchicago** [comment]
moved to the left
